name: Deploy to GitHub Pages

on:
  push:
    branches:
      gatsby-revamp

jobs:
  deploy_portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17
      
      - name: Install `gh-pages` Node Package
        run: npm install gh-pages --save-dev

      - name: Set Remote URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Build the site
        run: npm run build

      - name: Deploy to `master` using `gh-pages`
        run: npm run deploy-gh-action -- github-actions-bot <support+actions@github.com>

